#!/usr/bin/env python3
"""Extract Metal frontend facts from Apple-clang AST dumps.

The input format is Clang's text AST dump as published by metal-info.  The
script accepts local paths or raw URLs and never needs to clone metal-info.  It
extracts two kinds of facts that are stable and useful for bootstrapping a
clean-room Metal frontend:

  * implicit __metal_* builtin object type names
  * Apple AST Metal*Attr spellings observed in the dumps

It can also query the GitHub contents API for one metal-info artifact directory
and select AST dumps from multiple Metal language generations / fixtures.
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import re
import sys
import urllib.parse
import urllib.request

DEFAULT_FIXTURES = (
    "probe_min",
    "address_spaces_all",
    "attributes_all",
    "io_dump",
    "metal_object_types_all",
    "texture_read",
    "types_all",
    "stdlib_headers_all",
)

ATTR_ALIAS = {
    "MetalAttributeIndexAttr": "MetalAttributeAttr",
    "MetalBufferIndexAttr": "MetalBufferAttr",
    "MetalTextureIndexAttr": "MetalTextureAttr",
    "MetalSamplerIndexAttr": "MetalSamplerAttr",
    "MetalThreadPosGridAttr": "MetalThreadPositionInGridAttr",
    "MetalUserDefinedAttr": "MetalUserAttr",
    "MetalKernelAttr": "DeviceKernelAttr",
}

BUILTIN_RE = re.compile(r"implicit (__metal_[A-Za-z0-9_]+) '(__metal_[A-Za-z0-9_]+)'")
ATTR_RE = re.compile(r"\b(Metal[A-Za-z0-9_]*Attr)\b")
STD_RE = re.compile(r"_(?:macos|osx|ios|tvos|watchos)?-?metal(?P<std>[0-9]+\.[0-9]+)_")


def read_text(path_or_url: str) -> str:
    if path_or_url.startswith(("http://", "https://")):
        req = urllib.request.Request(path_or_url, headers={"User-Agent": "clang-metal-ast-table-gen"})
        with urllib.request.urlopen(req, timeout=60) as fh:
            return fh.read().decode("utf-8", errors="replace")
    return pathlib.Path(path_or_url).read_text(encoding="utf-8", errors="replace")


def github_json(url: str):
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "clang-metal-ast-table-gen",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as fh:
        return json.load(fh)


def discover_metal_info_inputs(repo: str, ref: str, artifact: str,
                               fixtures: tuple[str, ...]) -> list[str]:
    owner, name = repo.split("/", 1)
    api_path = urllib.parse.quote(f"reference/{artifact}/ast", safe="/")
    url = f"https://api.github.com/repos/{owner}/{name}/contents/{api_path}?ref={urllib.parse.quote(ref)}"
    rows = github_json(url)
    inputs: list[str] = []
    for row in rows:
        filename = row.get("name", "")
        if not filename.endswith("_ast-text.txt"):
            continue
        if fixtures and not any(f"_{fixture}_" in filename for fixture in fixtures):
            continue
        download_url = row.get("download_url")
        if download_url:
            inputs.append(download_url)
    return sorted(inputs)


def extract(inputs: list[str]):
    attrs = collections.Counter()
    builtins = collections.Counter()
    standards = collections.Counter()
    used_inputs: list[str] = []
    for item in inputs:
        try:
            text = read_text(item)
        except Exception as exc:
            print(f"warning: failed to read {item}: {exc}", file=sys.stderr)
            continue
        used_inputs.append(item)
        if m := STD_RE.search(pathlib.PurePosixPath(item).name):
            standards[m.group("std")] += 1
        for attr in ATTR_RE.findall(text):
            attrs[attr] += 1
        for builtin, spelling in BUILTIN_RE.findall(text):
            if builtin == spelling:
                builtins[builtin] += 1
    return used_inputs, attrs, builtins, standards


def emit_def(inputs: list[str], attrs, builtins, standards) -> str:
    out: list[str] = []
    out.append("//===--- MetalASTReference.def - Facts from Metal AST dumps ----*- C++ -*-===//")
    out.append("//")
    out.append("// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.")
    out.append("// See https://llvm.org/LICENSE.txt for license information.")
    out.append("// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception")
    out.append("//")
    out.append("//===----------------------------------------------------------------------===//")
    out.append("//")
    out.append("// Generated by clang/utils/metal/gen-metal-ast-support.py from Apple-clang")
    out.append("// AST dumps, typically from kagurasumusun/metal-info reference artifacts.")
    out.append("//")
    if standards:
        out.append("// Metal standards represented in scanned AST dumps:")
        for std, count in sorted(standards.items(), key=lambda kv: tuple(map(int, kv[0].split('.')))):
            out.append(f"//   metal{std}: {count} dump(s)")
        out.append("//")
    out.append(f"// Input AST dumps scanned: {len(inputs)}")
    out.append("//")
    out.append("// METAL_AST_BUILTIN_TYPE(__metal_foo_t)")
    out.append("// METAL_AST_ATTR(AppleASTAttrName)")
    out.append("// METAL_AST_ATTR_ALIAS(AppleASTAttrName, CurrentClangAttrName)")
    out.append("//")
    out.append("//===----------------------------------------------------------------------===//")
    out.append("")
    out.append("#ifndef METAL_AST_BUILTIN_TYPE")
    out.append("#define METAL_AST_BUILTIN_TYPE(Name)")
    out.append("#endif")
    out.append("#ifndef METAL_AST_ATTR")
    out.append("#define METAL_AST_ATTR(Name)")
    out.append("#endif")
    out.append("#ifndef METAL_AST_ATTR_ALIAS")
    out.append("#define METAL_AST_ATTR_ALIAS(AppleName, ClangName)")
    out.append("#endif")
    out.append("")
    for name, count in sorted(builtins.items()):
        out.append(f"// observed {count} time(s)")
        out.append(f"METAL_AST_BUILTIN_TYPE({name})")
    out.append("")
    for name, count in sorted(attrs.items()):
        out.append(f"// observed {count} time(s)")
        out.append(f"METAL_AST_ATTR({name})")
        if name in ATTR_ALIAS:
            out.append(f"METAL_AST_ATTR_ALIAS({name}, {ATTR_ALIAS[name]})")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--input", action="append", default=[], help="Local AST dump path or raw URL")
    parser.add_argument("--metal-info-repo", default="kagurasumusun/metal-info")
    parser.add_argument("--metal-info-ref", default="main")
    parser.add_argument("--artifact", default="metal-ast-macos-air64")
    parser.add_argument("--fixture", action="append", default=[], help="Fixture basename to select when discovering metal-info AST dumps")
    parser.add_argument("--discover-metal-info", action="store_true", help="Discover AST dumps from the metal-info GitHub API")
    args = parser.parse_args(argv)

    inputs = list(args.input)
    if args.discover_metal_info:
        fixtures = tuple(args.fixture) if args.fixture else DEFAULT_FIXTURES
        inputs.extend(discover_metal_info_inputs(args.metal_info_repo, args.metal_info_ref,
                                                 args.artifact, fixtures))
    if not inputs:
        parser.error("provide --input or --discover-metal-info")

    used_inputs, attrs, builtins, standards = extract(inputs)
    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(emit_def(used_inputs, attrs, builtins, standards), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
