#!/usr/bin/env python3
"""Extract __metal_* builtin entry points from Apple Metal stdlib headers.

The script reads local files or discovers the reference Apple clang resource
headers in kagurasumusun/metal-info via GitHub APIs, without cloning the repo.
It emits a simple .def table that can be used by future builtin registration,
Sema, and CodeGen lowering work.
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import pathlib
import re
import sys
import urllib.parse
import urllib.request

BUILTIN_RE = re.compile(r"\b(__metal_[A-Za-z0-9_]+)\b")


def request_headers() -> dict[str, str]:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "clang-metal-stdlib-builtin-gen",
    }
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def github_json(url: str):
    req = urllib.request.Request(url, headers=request_headers())
    with urllib.request.urlopen(req, timeout=60) as fh:
        return json.load(fh)


def read_text(path_or_url: str) -> str:
    if path_or_url.startswith(("http://", "https://")):
        req = urllib.request.Request(path_or_url, headers={"User-Agent": "clang-metal-stdlib-builtin-gen"})
        with urllib.request.urlopen(req, timeout=60) as fh:
            return fh.read().decode("utf-8", errors="replace")
    return pathlib.Path(path_or_url).read_text(encoding="utf-8", errors="replace")


def discover_headers(repo: str, ref: str, clang_version: str) -> list[str]:
    owner, name = repo.split("/", 1)
    root = f"reference-apple/clang/{clang_version}/include/metal"
    root_url = (
        f"https://api.github.com/repos/{owner}/{name}/contents/"
        f"{urllib.parse.quote(root, safe='/')}?ref={urllib.parse.quote(ref)}"
    )
    rows = github_json(root_url)
    urls: list[str] = []
    stack = [row for row in rows]
    while stack:
        row = stack.pop()
        if row.get("type") == "dir":
            child_rows = github_json(row["url"])
            stack.extend(child_rows)
            continue
        if row.get("type") != "file":
            continue
        path = row.get("path", "")
        base = pathlib.PurePosixPath(path).name
        # Metal stdlib headers are mostly extensionless plus a few .h/modulemap
        # files.  Skip module maps but keep .h and extensionless headers.
        if base.endswith(".modulemap") or base == "module.modulemap":
            continue
        if row.get("download_url"):
            urls.append(row["download_url"])
    return sorted(urls)


def emit(counter: collections.Counter[str], sources: int) -> str:
    out: list[str] = []
    out.append("//===--- MetalStdlibBuiltins.def - Metal stdlib builtin names -*- C++ -*-===//")
    out.append("//")
    out.append("// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.")
    out.append("// See https://llvm.org/LICENSE.txt for license information.")
    out.append("// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception")
    out.append("//")
    out.append("//===----------------------------------------------------------------------===//")
    out.append("//")
    out.append("// Generated by clang/utils/metal/gen-metal-stdlib-builtins.py from Apple")
    out.append("// Metal stdlib headers, usually via kagurasumusun/metal-info raw files.")
    out.append(f"// Header inputs scanned: {sources}")
    out.append(f"// Unique __metal_* builtin names: {len(counter)}")
    out.append("//")
    out.append("// METAL_STDLIB_BUILTIN(Name)")
    out.append("//")
    out.append("//===----------------------------------------------------------------------===//")
    out.append("")
    out.append("#ifndef METAL_STDLIB_BUILTIN")
    out.append("#define METAL_STDLIB_BUILTIN(Name)")
    out.append("#endif")
    out.append("")
    for name, count in sorted(counter.items()):
        out.append(f"// observed {count} time(s)")
        out.append(f"METAL_STDLIB_BUILTIN({name})")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--input", action="append", default=[])
    parser.add_argument("--discover-metal-info", action="store_true")
    parser.add_argument("--metal-info-repo", default="kagurasumusun/metal-info")
    parser.add_argument("--metal-info-ref", default="main")
    parser.add_argument("--apple-clang-version", default="32023.883")
    args = parser.parse_args(argv)

    inputs = list(args.input)
    if args.discover_metal_info:
        inputs.extend(discover_headers(args.metal_info_repo, args.metal_info_ref,
                                       args.apple_clang_version))
    inputs = sorted(dict.fromkeys(inputs))
    if not inputs:
        parser.error("provide --input or --discover-metal-info")

    counter: collections.Counter[str] = collections.Counter()
    for item in inputs:
        try:
            text = read_text(item)
        except Exception as exc:
            print(f"warning: failed to read {item}: {exc}", file=sys.stderr)
            continue
        counter.update(BUILTIN_RE.findall(text))

    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(emit(counter, len(inputs)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
