#!/usr/bin/env python3
"""Generate lightweight Metal AIR support tables.

This script intentionally does not clone metal-info.  It can be run with only
local files or raw GitHub URLs and emits the small table Clang currently uses for
its early Metal/AIR bring-up.  The table is deliberately conservative: it covers
common scalar/vector aliases and the AIR generated(...) fragments observed in the
metal-info reference IR for simple IO fixtures.

Examples:
  python3 clang/utils/metal/gen-metal-air-support.py \
    --output clang/include/clang/Basic/MetalAIRTypes.def

  python3 clang/utils/metal/gen-metal-air-support.py \
    --scan-ir https://raw.githubusercontent.com/kagurasumusun/metal-info/main/reference/metal-ast-macos-air64/ir/macos_air64_versioned_none_macos-metal2.0_io_dump_10_15_llvm-ir.ll \
    --output clang/include/clang/Basic/MetalAIRTypes.def
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import urllib.request

TYPE_ROWS = [
    ("uchar", "unsigned char", "uchar", "h"),
    ("ushort", "unsigned short", "ushort", "t"),
    ("uint", "unsigned int", "uint", "j"),
    ("ulong", "unsigned long", "ulong", "m"),
    ("float2", "float __attribute__((ext_vector_type(2)))", "float2", "Dv2_f"),
    ("float3", "float __attribute__((ext_vector_type(3)))", "float3", "Dv3_f"),
    ("float4", "float __attribute__((ext_vector_type(4)))", "float4", "Dv4_f"),
    ("half2", "__fp16 __attribute__((ext_vector_type(2)))", "half2", "Dv2_Dh"),
    ("half3", "__fp16 __attribute__((ext_vector_type(3)))", "half3", "Dv3_Dh"),
    ("half4", "__fp16 __attribute__((ext_vector_type(4)))", "half4", "Dv4_Dh"),
    ("int2", "int __attribute__((ext_vector_type(2)))", "int2", "Dv2_i"),
    ("int3", "int __attribute__((ext_vector_type(3)))", "int3", "Dv3_i"),
    ("int4", "int __attribute__((ext_vector_type(4)))", "int4", "Dv4_i"),
    ("uint2", "uint __attribute__((ext_vector_type(2)))", "uint2", "Dv2_j"),
    ("uint3", "uint __attribute__((ext_vector_type(3)))", "uint3", "Dv3_j"),
    ("uint4", "uint __attribute__((ext_vector_type(4)))", "uint4", "Dv4_j"),
    ("float2x2", "float __attribute__((ext_vector_type(4)))", "float2x2", ""),
    ("float4x4", "float __attribute__((ext_vector_type(16)))", "float4x4", ""),
]

GENERATED_RE = re.compile(r"generated\((?P<body>[^)]*)\)")


def read_text(path_or_url: str) -> str:
    if path_or_url.startswith(("http://", "https://")):
        req = urllib.request.Request(path_or_url, headers={"User-Agent": "clang-metal-air-table-gen"})
        with urllib.request.urlopen(req, timeout=60) as fh:
            return fh.read().decode("utf-8", errors="replace")
    return pathlib.Path(path_or_url).read_text(encoding="utf-8", errors="replace")


def scan_generated_names(inputs: list[str]) -> set[str]:
    names: set[str] = set()
    for item in inputs:
        text = read_text(item)
        for match in GENERATED_RE.finditer(text):
            names.add(match.group("body"))
    return names


def emit_def(scanned: set[str]) -> str:
    out: list[str] = []
    out.append("//===--- MetalAIRTypes.def - Metal AIR type table -------------*- C++ -*-===//")
    out.append("//")
    out.append("// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.")
    out.append("// See https://llvm.org/LICENSE.txt for license information.")
    out.append("// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception")
    out.append("//")
    out.append("//===----------------------------------------------------------------------===//")
    out.append("//")
    out.append("// This file is generated by clang/utils/metal/gen-metal-air-support.py.")
    if scanned:
        out.append("//")
        out.append("// generated(...) names seen while scanning reference IR:")
        for name in sorted(scanned):
            out.append(f"//   {name}")
    out.append("//")
    out.append("// METAL_AIR_TYPE(Name, CType, AIRName, AIRItaniumMangle)")
    out.append("//")
    out.append("//===----------------------------------------------------------------------===//")
    out.append("")
    out.append("#ifndef METAL_AIR_TYPE")
    out.append("#error \"Define METAL_AIR_TYPE before including MetalAIRTypes.def\"")
    out.append("#endif")
    out.append("")
    for name, ctype, air_name, mangle in TYPE_ROWS:
        out.append(f'METAL_AIR_TYPE({name}, "{ctype}", "{air_name}", "{mangle}")')
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, help="Output MetalAIRTypes.def path")
    parser.add_argument("--scan-ir", action="append", default=[], help="Optional local path or raw URL to AIR LLVM IR to annotate generated(...) observations")
    args = parser.parse_args(argv)

    scanned = scan_generated_names(args.scan_ir)
    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(emit_def(scanned), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
