#!/usr/bin/env python3
"""Generate clang's bootstrap Metal stdlib prototype table.

This is intentionally conservative: it uses a curated map for common scalar
builtins and filters it through MetalStdlibBuiltins.def so the generated table
only contains names observed in the Apple Metal headers.  Future revisions can
replace the curated map with parsed Apple header signatures from metal-info.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

PROTOTYPES = {
    "__metal_abs": 'extern "C" int __metal_abs(int);',
    "__metal_select": 'extern "C" int __metal_select(int, int, bool);',
    "__metal_acos": 'extern "C" float __metal_acos(float);',
    "__metal_asin": 'extern "C" float __metal_asin(float);',
    "__metal_atan": 'extern "C" float __metal_atan(float);',
    "__metal_ceil": 'extern "C" float __metal_ceil(float);',
    "__metal_cos": 'extern "C" float __metal_cos(float);',
    "__metal_exp": 'extern "C" float __metal_exp(float);',
    "__metal_exp2": 'extern "C" float __metal_exp2(float);',
    "__metal_floor": 'extern "C" float __metal_floor(float);',
    "__metal_log": 'extern "C" float __metal_log(float);',
    "__metal_log2": 'extern "C" float __metal_log2(float);',
    "__metal_rsqrt": 'extern "C" float __metal_rsqrt(float);',
    "__metal_sin": 'extern "C" float __metal_sin(float);',
    "__metal_sqrt": 'extern "C" float __metal_sqrt(float);',
    "__metal_trunc": 'extern "C" float __metal_trunc(float);',
    "__metal_clamp": 'extern "C" float __metal_clamp(float, float, float);',
    "__metal_fmax": 'extern "C" float __metal_fmax(float, float);',
    "__metal_fmin": 'extern "C" float __metal_fmin(float, float);',
    "__metal_pow": 'extern "C" float __metal_pow(float, float);',
}

HEADER = """//===--- MetalStdlibBuiltinPrototypes.def - Metal stdlib prototypes -*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Generated by clang/utils/metal/gen-metal-stdlib-prototypes.py.
// Bootstrap exact prototypes for a small common subset of __metal_* stdlib
// entry points.  These declarations supplement MetalStdlibBuiltins.def, whose
// remaining callable rows still use a generic fallback until a fuller Apple
// header signature extractor is wired in.
//
// METAL_STDLIB_BUILTIN_PROTO(Name, PrototypeString)
//
//===----------------------------------------------------------------------===//

#ifndef METAL_STDLIB_BUILTIN_PROTO
#define METAL_STDLIB_BUILTIN_PROTO(Name, PrototypeString)
#endif

"""


def observed_names(path: Path) -> set[str]:
    rx = re.compile(r"METAL_STDLIB_BUILTIN\((__metal_[A-Za-z0-9_]+)\)")
    return {m.group(1) for m in rx.finditer(path.read_text())}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdlib-builtins", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    seen = observed_names(args.stdlib_builtins)
    lines = [HEADER]
    for name in sorted(PROTOTYPES):
        if name not in seen:
            continue
        prototype = PROTOTYPES[name].replace('"', r'\"')
        lines.append(
            f'METAL_STDLIB_BUILTIN_PROTO({name}, "{prototype}")\n'
        )
    args.output.write_text("".join(lines))


if __name__ == "__main__":
    main()
